migrated your code to python 3 with minor changes in library
amanvishnani/SongsPk-MusicScrapper pull request #3
Opened 2019-04-14 11:42 UTC by maheshmnj

2019-04-15 06:58 UTC, amanvishnani requested changes
Please find below changes and correct them before I merge this request.

1. Add `requirements.txt` file with `requests` as a dependency in it.
2. Please find changes in the comment section of code

2019-04-15 06:58 UTC, amanvishnani commented on download.py
>              links = re.findall('<td class="songs-bitrate-1"><i class="fa fa-music"></i>(.+?)<em>',content)
`content.text`

2019-04-15 06:58 UTC, amanvishnani commented on download.py
>          tags = re.findall('<li class="list">.*?</li>',content.read())
change `content.read()` to `content.text`

2019-04-15 06:58 UTC, amanvishnani commented on download.py
>                  cover = re.findall('<img data-retina="" src="(.+?)"',content)[0]
change `content` to `content.text`

2019-04-15 06:58 UTC, amanvishnani commented on download.py
>          url = 'https://www.songspk.cloud/indian_movie/'+page+'_List.html'
change `www.songspk.cloud` to `www.songspk.run`

2019-04-15 07:02 UTC, amanvishnani requested changes

2019-04-15 07:02 UTC, amanvishnani commented on README.md
>  - Clone this repository `git clone`
After Clone this repository, add ` pip install -r requirements.txt`

2019-04-16 04:46 UTC, maheshmnj commented
I wii make the changes soon

2019-04-19 03:45 UTC, maheshmnj commented
> Please find below changes and correct them before I merge this request.
> 
> 1. Add `requirements.txt` file with `requests` as a dependency in it.
> 2. Please find changes in the comment section of code

I couldnt understand this I made rest of the changes but it gives an error content not found after changing content to content.text

2019-04-19 19:15 UTC, amanvishnani commented on download.py
>              links = re.findall('<td class="songs-bitrate-1"><i class="fa fa-music"></i>(.+?)<em>',content)
Please Find the following changes..
```links = re.findall('<td class="songs-bitrate-1"><i class="fa fa-music"></i>(.+?)<em>',content.text)```
change content to content.text in re.findall() second parameter.

2019-04-19 19:15 UTC, amanvishnani commented on download.py
>          tags = re.findall('<li class="list">.*?</li>',content.read())
``` tags = re.findall('<li class="list">.*?</li>',content.read())```
to 
``` tags = re.findall('<li class="list">.*?</li>',content.text)```

2019-04-19 19:21 UTC, amanvishnani commented
Please read about [Requirements Files here](https://pip.pypa.io/en/stable/user_guide/#requirements-files)

> Logically, a Requirements file is just a list of pip install arguments placed in a file. 

I need this because you are using ```requests``` package which a user might not have.

Please Make changes to your master and its commit will be reflected here. You don't have to open a new pull request for that.

2019-04-20 04:31 UTC, maheshmnj commented
You can check the code now
two take aways for me from this project 

- `pip3 freeze > requirements.txt`
is much simpler to automatically add all the requirements for the project
- you don't need to submit a new pull request every time a commit to the forked repo synchronizes with the pull request xD

2019-04-20 05:31 UTC, amanvishnani approved these changes

2019-04-20 05:34 UTC, amanvishnani commented
> You can check the code now
> two take aways for me from this project
> 
> * `pip3 freeze > requirements.txt`
>   is much simpler to automatically add all the requirements for the project
> * you don't need to submit a new pull request every time a commit to the forked repo synchronizes with the pull request xD

Yeah, ```pip3 freeze``` is a convenient command but we need to remove unwanted dependencies from it.
Anyways I will do it after merge.

2019-04-20 05:37 UTC, amanvishnani commented
closes #4

2019-04-20 05:37 UTC, merged